### ISSUE TITLE
Unable to see Wekan image

### ISSUE THREAD

**Issue by prateek2408** [cloudflavor/wekan-cloud#1]
Hey,

I was trying to use your yaml in K8S but I can see that you have specified MongoDB in the containers but no wekan container, How would wekan be installed here .

Let me know in case I missed something.

Regards,
Prateek

**Comment by PI-Victor** [comment]
hey @prateek2408, actually i never finished this and i've been wanting to finish it for quite some time now.
I'll try to push some updates this week, but i can't really guarantee that at this point.
